name: health check and ci
on:
  push:
    branches: [develop, master, main]
  pull_request:
    branches: [develop, master, main]
jobs:
  process:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use node 16.x
      - uses: actions/setup-node@v2
      - with: 
          node-version: 16.x
      - name: Install dependencies
      - run: npm ci
      - name: Run Test
      - run: npm run lint
      - run: npm run test
      - name: Run build
      - run: npm run build
      - run: echo "status = ${{ job.status }}."
